spring:
  application:
    name: BlogGateway
server:
  port: 2080

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://blogmanager:123456@master:10237/eureka/
